spring:
  application:
    name: pixel-battle
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


management:
  endpoints:
    web:
      exposure:
        include: health

game:
  width: 1000
  height: 1000
  cooldown: 10

jwt:
  secret: ${JWT_SECRET}
  access-token-duration-ms: 300000
  refresh-token-duration-ms: 604800000