name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Set version from tag
      - name: Set version
        id: set-version
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Set repository name in lowercase
      - name: Set repository name
        id: set-repo-name
        run: |
          REPO_NAME=$(basename "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "OWNER_NAME=$OWNER_NAME" >> $GITHUB_ENV

      # Run style checks and tests
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run checks and tests
        run: ./gradlew check test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixel-battle-be:${VERSION} .
          docker push ${{ secrets.DOCKER_USERNAME }}/pixel-battle-be:${VERSION}
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/pixel-battle-be:${VERSION} \
                     ${{ secrets.DOCKER_USERNAME }}/pixel-battle-be:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pixel-battle-be:latest

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile \
            -t ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION} .
          docker push ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION}

          docker tag ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION} \
                     ghcr.io/$OWNER_NAME/$REPO_NAME:latest
          docker push ghcr.io/$OWNER_NAME/$REPO_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: prod
    steps:
      - name: Checkout only docker-compose.yaml
        uses: actions/checkout@v3
        with:
          sparse-checkout: docker-compose.yaml
          fetch-depth: 1
      - name: Copy docker-compose
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            docker-compose.yml
          target: /srv/pixel-battle/

      - name: Deploy containers via docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/pixel-battle
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}
            
            docker compose -p pixel-battle up -d --pull always
            docker image prune -f
